\set ON_ERROR_STOP on
-- Datos sintéticos; B57/B48/B56 son reales y AD3-102..105 son dobles declarados.
CREATE FUNCTION public.b57_proponer(a text)
RETURNS text LANGUAGE plpgsql SECURITY INVOKER SET search_path=pg_catalog SET timezone='UTC' AS $f$
DECLARE h text; p text; r text; c text; cap bytea; d bytea; cx bytea;
BEGIN
 h:=encode(sha256(convert_to(array_to_string(ARRAY['bolsa.causa_participacion.v1','actualizacion_contacto','2','Datos de contacto verificados','false','true','true','true'],E'\n'),'UTF8')),'hex');
 p:='propuesta:causa:'||encode(sha256(convert_to('bolsa.causa_participacion.propuesta.v1'||E'\n'||h||E'\n'||a,'UTF8')),'hex'); r:='recibo:propuesta:causa:'||encode(sha256(convert_to('bolsa.causa_participacion.propuesta.recibo.v1'||E'\n'||p,'UTF8')),'hex');
 c:=encode(sha256(convert_to('{"ambitos":{},"atributos":{"causa_sha256":"'||h||'","propuesta_ref":"'||p||'","recibo_ref":"'||r||'"}}','UTF8')),'hex');
 cap:=convert_to(jsonb_build_object('audiencia_consumo','vec_bolsa_llamamientos.causas_participacion.proponer.v1','operacion','bolsa.causas_participacion.proponer','efecto_ref','vec.bolsa.causas_participacion','huella_efecto_sha256',c)::text,'UTF8');
 d:=convert_to(jsonb_build_object('principal_id',a,'accion','bolsa.causas_participacion.proponer','modulo_id','bolsa','tipo_recurso','catalogo_causas_participacion','finalidad','preparar_catalogo_causas_participacion','recurso_ref','vec.bolsa.causas_participacion','contexto_recurso_huella_sha256',c,'campos_permitidos',jsonb_build_array('borrador','recibo'),'obligaciones','[]'::jsonb)::text,'UTF8');
 cx:=convert_to(jsonb_build_object('esquema','vec.contexto-actor.vinculado.v2','principal_ref',a,'persona_ref',CASE WHEN a IN ('actor:rrhh:proponente','actor:rrhh:otro_cert') THEN 'per_aaaaaaaaaaaaaaaaaaaaaa' ELSE 'per_bbbbbbbbbbbbbbbbbbbbbb' END)::text,'UTF8');
 PERFORM * FROM vec_bolsa_llamamientos.proponer_causa_participacion_v1('actualizacion_contacto',2,'Datos de contacto verificados',false,true,true,true,h,a,p,r,cap,d,'{}',cx,1,1,'{}','{}','{}','{}'); RETURN p;
END $f$;
CREATE FUNCTION public.b57_get(a text,p text) RETURNS text LANGUAGE plpgsql SECURITY INVOKER SET search_path=pg_catalog SET timezone='UTC' AS $f$
DECLARE c text; cap bytea; d bytea; x record;
BEGIN c:=encode(sha256(convert_to('{"ambitos":{},"atributos":{"propuesta_ref":"'||p||'"}}','UTF8')),'hex'); cap:=convert_to(jsonb_build_object('audiencia_consumo','vec_bolsa_llamamientos.causas_participacion.propuesta.consultar.v1','operacion','bolsa.causas_participacion.propuesta.consultar','efecto_ref',p,'huella_efecto_sha256',c)::text,'UTF8'); d:=convert_to(jsonb_build_object('principal_id',a,'accion','bolsa.causas_participacion.propuesta.consultar','modulo_id','bolsa','tipo_recurso','propuesta_catalogo_causas_participacion','finalidad','revisar_propuesta_catalogo_causas_participacion','recurso_ref',p,'contexto_recurso_huella_sha256',c,'campos_permitidos',jsonb_build_array('estado','propuesta','recibo'),'obligaciones','[]'::jsonb)::text,'UTF8'); SELECT * INTO x FROM vec_bolsa_llamamientos.consultar_propuesta_causa_participacion_v1(p,a,cap,d,'{}','{}',1,1,'{}','{}','{}','{}'); RETURN x.estado; END $f$;
CREATE FUNCTION public.b57_publicar(a text,p text,alterada boolean DEFAULT false) RETURNS text LANGUAGE plpgsql SECURITY INVOKER SET search_path=pg_catalog SET timezone='UTC' AS $f$
DECLARE e text:=CASE WHEN alterada THEN 'Etiqueta alterada' ELSE 'Datos de contacto verificados' END; h text; r text; c text; cap bytea; d bytea; cx bytea; x record;
BEGIN h:=encode(sha256(convert_to(array_to_string(ARRAY['bolsa.causa_participacion.v1','actualizacion_contacto','2',e,'false','true','true','true'],E'\n'),'UTF8')),'hex'); r:='recibo:causa:'||encode(sha256(convert_to('bolsa.causa_participacion.recibo.v1'||E'\n'||h,'UTF8')),'hex'); c:=encode(sha256(convert_to('{"ambitos":{},"atributos":{"causa_sha256":"'||h||'","propuesta_ref":"'||p||'","recibo_ref":"'||r||'"}}','UTF8')),'hex'); cap:=convert_to(jsonb_build_object('audiencia_consumo','vec_bolsa_llamamientos.causas_participacion.publicar.v1','operacion','bolsa.causas_participacion.publicar','efecto_ref','vec.bolsa.causas_participacion','huella_efecto_sha256',c)::text,'UTF8'); d:=convert_to(jsonb_build_object('principal_id',a,'accion','bolsa.causas_participacion.publicar','modulo_id','bolsa','tipo_recurso','catalogo_causas_participacion','finalidad','gestionar_catalogo_causas_participacion','recurso_ref','vec.bolsa.causas_participacion','contexto_recurso_huella_sha256',c,'campos_permitidos',jsonb_build_array('catalogo','recibo'),'obligaciones','[]'::jsonb)::text,'UTF8'); cx:=convert_to(jsonb_build_object('esquema','vec.contexto-actor.vinculado.v2','principal_ref',a,'persona_ref',CASE WHEN a IN ('actor:rrhh:proponente','actor:rrhh:otro_cert') THEN 'per_aaaaaaaaaaaaaaaaaaaaaa' ELSE 'per_bbbbbbbbbbbbbbbbbbbbbb' END)::text,'UTF8'); SELECT * INTO x FROM vec_bolsa_llamamientos.publicar_causa_participacion_v1('actualizacion_contacto',2,e,false,true,true,true,h,a,r,cap,d,'{}',cx,1,1,'{}','{}','{}','{}',p); RETURN x.recibo_ref; END $f$;
REVOKE ALL ON FUNCTION public.b57_proponer(text),public.b57_get(text,text),public.b57_publicar(text,text,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.b57_proponer(text),public.b57_get(text,text),public.b57_publicar(text,text,boolean) TO vec_b57_rrhh,vec_b57_revisor;
SET ROLE vec_bolsa_llamamientos_propietario;
DO $v$ DECLARE h text; BEGIN h:=vec_bolsa_llamamientos.huella_causa_participacion_v1('prueba_utf8',1,'Cambio: áéñ;|:',true,false,true,true); IF h<>'9fc9fb53485b81871467f6093badad8dc2dfdd871448aec773a96ba9570389f4' OR h=vec_bolsa_llamamientos.huella_causa_participacion_v1('prueba_utf8',1,'Cambio: áéñ;|:',true,false,true,true) THEN RAISE EXCEPTION 'vector UTF8 B57'; END IF; INSERT INTO vec_bolsa_llamamientos.situacion_participacion VALUES('participacion:1','2026-09-28 09:00Z','disponible',NULL,'texto libre B2','actor:historico','clave:b2','recibo:b2','2026-09-28 09:00Z'); INSERT INTO vec_bolsa_llamamientos.datos_contacto_participacion VALUES('participacion:1',1,'clave:hist','\x01','\x02','texto libre B4','actor:historico','2026-09-28 09:01Z','clave:b4','recibo:b4'); END $v$;
RESET ROLE;
SET SESSION AUTHORIZATION vec_b57_rrhh; BEGIN; SET TRANSACTION ISOLATION LEVEL SERIALIZABLE; SET LOCAL timezone='UTC';
DO $p$ DECLARE r text; no boolean:=false; BEGIN r:=public.b57_proponer('actor:rrhh:proponente'); IF r<>public.b57_proponer('actor:rrhh:proponente') THEN RAISE EXCEPTION 'replay propuesta'; END IF; BEGIN PERFORM public.b57_publicar('actor:rrhh:proponente',r); EXCEPTION WHEN insufficient_privilege THEN no:=true; END; IF NOT no THEN RAISE EXCEPTION 'mismo actor publica'; END IF; no:=false; BEGIN PERFORM public.b57_publicar('actor:rrhh:otro_cert',r); EXCEPTION WHEN insufficient_privilege THEN no:=true; END; IF NOT no THEN RAISE EXCEPTION 'misma persona con otro actor publicó'; END IF; no:=false; BEGIN PERFORM public.b57_publicar('actor:rrhh:proponente',r,true); EXCEPTION WHEN sqlstate 'VBS01' THEN no:=true; END; IF NOT no THEN RAISE EXCEPTION 'propuesta alterada'; END IF; END $p$; COMMIT; RESET SESSION AUTHORIZATION;
SET SESSION AUTHORIZATION vec_b57_revisor; BEGIN; SET TRANSACTION ISOLATION LEVEL SERIALIZABLE; SET LOCAL timezone='UTC';
DO $r$ DECLARE h text; p text; n integer; BEGIN h:=encode(sha256(convert_to(array_to_string(ARRAY['bolsa.causa_participacion.v1','actualizacion_contacto','2','Datos de contacto verificados','false','true','true','true'],E'\n'),'UTF8')),'hex'); p:='propuesta:causa:'||encode(sha256(convert_to('bolsa.causa_participacion.propuesta.v1'||E'\n'||h||E'\nactor:rrhh:proponente','UTF8')),'hex'); IF public.b57_get('actor:rrhh:revisor',p)<>'pendiente' THEN RAISE EXCEPTION 'GET pendiente'; END IF; PERFORM public.b57_publicar('actor:rrhh:revisor',p); PERFORM public.b57_publicar('actor:rrhh:revisor',p); IF public.b57_get('actor:rrhh:revisor',p)<>'publicada' THEN RAISE EXCEPTION 'GET publicada'; END IF; SELECT count(*) INTO n FROM vec_bolsa_llamamientos.recuperar_datos_contacto_participacion_v2('participacion:1','clave:b4') WHERE causa_codigo IS NULL; IF n<>1 THEN RAISE EXCEPTION 'B4 reescrita'; END IF; END $r$; COMMIT; RESET SESSION AUTHORIZATION;
DO $acl$ BEGIN IF has_table_privilege('vec_b57_rrhh','vec_bolsa_llamamientos.propuesta_causa_participacion','SELECT') OR has_table_privilege('vec_b57_revisor','vec_bolsa_llamamientos.causa_participacion_catalogo','SELECT') OR has_function_privilege('vec_b57_sin_permiso','vec_bolsa_llamamientos.proponer_causa_participacion_v1(text,bigint,text,boolean,boolean,boolean,boolean,text,text,text,text,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)','EXECUTE') THEN RAISE EXCEPTION 'ACL B57 abierta'; END IF; END $acl$;
