package ports

import (
	"context"

	"vec-diputacion-granada/internal/vec/domain"
)

const SuperficieAuditoriaFronteraRutaExactaContratacionTemporal = domain.SuperficieAuditoriaFronteraRutaExactaContratacionTemporal
const SuperficieAuditoriaFronteraRutaExactaOrganizacionHistoricaPersonal = domain.SuperficieAuditoriaFronteraRutaExactaOrganizacionHistoricaPersonal
const SuperficieAuditoriaFronteraRutaExactaPersonal = domain.SuperficieAuditoriaFronteraRutaExactaPersonal
const SuperficieAuditoriaFronteraRutaExactaAuditoria = domain.SuperficieAuditoriaFronteraRutaExactaAuditoria
const SuperficieAuditoriaFronteraRutaExactaUsuariosPreferencias = domain.SuperficieAuditoriaFronteraRutaExactaUsuariosPreferencias
const SuperficieAuditoriaFronteraRutaExactaBolsaCandidato = domain.SuperficieAuditoriaFronteraRutaExactaBolsaCandidato
const SuperficieAuditoriaFronteraRutaExactaAspirantes = domain.SuperficieAuditoriaFronteraRutaExactaAspirantes
const SuperficieAuditoriaFronteraRutaExactaSeleccionPreparacionBases = domain.SuperficieAuditoriaFronteraRutaExactaSeleccionPreparacionBases
const SuperficieAuditoriaFronteraRutaExactaBolsaReglasBaremo = domain.SuperficieAuditoriaFronteraRutaExactaBolsaReglasBaremo

var ErrOrdenAuditoriaFronteraRutaExactaInvalida = domain.ErrOrdenAuditoriaFronteraRutaExactaInvalida

type MotivoAuditoriaFronteraRutaExacta = domain.MotivoAuditoriaFronteraRutaExacta

const (
	MotivoAuditoriaFronteraRutaExactaAutenticacionRequerida = domain.MotivoAuditoriaFronteraRutaExactaAutenticacionRequerida
	MotivoAuditoriaFronteraRutaExactaAccesoDenegado         = domain.MotivoAuditoriaFronteraRutaExactaAccesoDenegado
)

// OrdenAuditoriaFronteraRutaExacta conserva la firma de los consumidores del
// puerto; las reglas de la orden pertenecen al dominio.
type OrdenAuditoriaFronteraRutaExacta = domain.OrdenAuditoriaFronteraRutaExacta

// RegistradorAuditoriaFronteraRutaExacta es una dependencia inyectada de la
// frontera HTTP. Su error nunca altera la denegación ya decidida.
type RegistradorAuditoriaFronteraRutaExacta interface {
	RegistrarAuditoriaFronteraRutaExacta(context.Context, OrdenAuditoriaFronteraRutaExacta) error
}
