\set ON_ERROR_STOP on
BEGIN;
SET LOCAL search_path=pg_catalog;
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname=current_user AND rolsuper) OR to_regnamespace('vec_dietas') IS NOT NULL OR EXISTS(SELECT 1 FROM pg_roles WHERE rolname IN ('vec_dietas_propietario','vec_dietas_migrador','vec_dietas_ejecutor')) THEN RAISE EXCEPTION 'bootstrap Dietas incompatible' USING ERRCODE='55000'; END IF;
END $$;
CREATE ROLE vec_dietas_propietario NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE vec_dietas_migrador NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE vec_dietas_ejecutor NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION NOBYPASSRLS;
GRANT vec_dietas_propietario TO vec_dietas_migrador WITH ADMIN FALSE, INHERIT FALSE, SET TRUE;
CREATE SCHEMA vec_dietas AUTHORIZATION vec_dietas_propietario;
REVOKE ALL ON SCHEMA vec_dietas FROM PUBLIC;
GRANT USAGE ON SCHEMA vec_dietas TO vec_dietas_migrador,vec_dietas_ejecutor;
ALTER DEFAULT PRIVILEGES FOR ROLE vec_dietas_propietario REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE vec_dietas_propietario REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
COMMIT;
