\set ON_ERROR_STOP on
BEGIN;
SET LOCAL ROLE vec_bolsa_llamamientos_propietario;
SET LOCAL search_path=pg_catalog;
SET LOCAL timezone='UTC';
SELECT pg_advisory_xact_lock(hashtextextended('vec_bolsa_llamamientos:migracion:000017',0));
DO $pre$ BEGIN
 IF to_regprocedure('vec_autorizacion_atestada_v3.registrar_y_consumir_emision_llamamiento_v3_atestada(bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)') IS NULL OR to_regclass('vec_bolsa_llamamientos.contacto_participacion') IS NULL OR to_regclass('vec_bolsa_llamamientos.datos_contacto_participacion') IS NULL THEN RAISE EXCEPTION 'dependencias B7 ausentes' USING ERRCODE='55000'; END IF;
END $pre$;
DO $bitacora$
DECLARE accion text; ruta text; resultado text;
BEGIN
 SELECT pg_get_constraintdef(oid,true) INTO STRICT accion FROM pg_constraint WHERE conrelid='vec_bolsa_llamamientos.bitacora_intento_borrador_llamamiento'::regclass AND conname='bitacora_intento_borrador_llamamiento_accion_check' AND contype='c';
	 SELECT pg_get_constraintdef(oid,true) INTO STRICT ruta FROM pg_constraint WHERE conrelid='vec_bolsa_llamamientos.bitacora_intento_borrador_llamamiento'::regclass AND conname='bitacora_intento_borrador_llamamiento_ruta_clase_check' AND contype='c';
	 SELECT pg_get_constraintdef(oid,true) INTO STRICT resultado FROM pg_constraint WHERE conrelid='vec_bolsa_llamamientos.bitacora_intento_borrador_llamamiento'::regclass AND conname='bitacora_intento_borrador_llamamiento_resultado_check' AND contype='c';
	 IF strpos(accion,'''consultar_datos_contacto''')<>0 OR strpos(accion,'''emitir_llamamiento''')<>0 OR strpos(accion,'''recuperar_llamamiento''')<>0 OR strpos(ruta,'''emisiones''')<>0 OR strpos(resultado,'''correcto''')<>0 OR strpos(accion,'CHECK (accion = ANY (ARRAY[')<>1 OR right(accion,3)<>']))' OR strpos(ruta,'CHECK (ruta_clase = ANY (ARRAY[')<>1 OR right(ruta,3)<>']))' OR strpos(resultado,'CHECK (resultado = ANY (ARRAY[')<>1 OR right(resultado,3)<>']))' THEN RAISE EXCEPTION 'bitácora de frontera incompatible con B7' USING ERRCODE='55000'; END IF;
 ALTER TABLE vec_bolsa_llamamientos.bitacora_intento_borrador_llamamiento DROP CONSTRAINT bitacora_intento_borrador_llamamiento_accion_check;
 EXECUTE 'ALTER TABLE vec_bolsa_llamamientos.bitacora_intento_borrador_llamamiento ADD CONSTRAINT bitacora_intento_borrador_llamamiento_accion_check '||left(accion,length(accion)-3)||', ''consultar_datos_contacto''::text, ''emitir_llamamiento''::text, ''recuperar_llamamiento''::text]))';
 ALTER TABLE vec_bolsa_llamamientos.bitacora_intento_borrador_llamamiento DROP CONSTRAINT bitacora_intento_borrador_llamamiento_ruta_clase_check;
	 EXECUTE 'ALTER TABLE vec_bolsa_llamamientos.bitacora_intento_borrador_llamamiento ADD CONSTRAINT bitacora_intento_borrador_llamamiento_ruta_clase_check '||left(ruta,length(ruta)-3)||', ''emisiones''::text]))';
	 ALTER TABLE vec_bolsa_llamamientos.bitacora_intento_borrador_llamamiento DROP CONSTRAINT bitacora_intento_borrador_llamamiento_resultado_check;
	 EXECUTE 'ALTER TABLE vec_bolsa_llamamientos.bitacora_intento_borrador_llamamiento ADD CONSTRAINT bitacora_intento_borrador_llamamiento_resultado_check '||left(resultado,length(resultado)-3)||', ''correcto''::text]))';
END $bitacora$;
CREATE OR REPLACE FUNCTION vec_bolsa_llamamientos.registrar_intento_borrador_llamamiento_v1(p_correlacion_ref text,p_accion text,p_ruta_clase text,p_actor_ref text,p_resultado text) RETURNS void LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog SET lock_timeout='2s' AS $f$
DECLARE v_ref text; BEGIN
 PERFORM vec_bolsa_llamamientos.exigir_runtime_registrador_frontera_borrador_llamamiento();
	 IF p_correlacion_ref IS NULL OR p_correlacion_ref !~ '^[A-Za-z0-9][A-Za-z0-9:._/-]{7,191}$' OR p_accion NOT IN('crear','consultar','cambiar_situacion','registrar_contacto','consultar_datos_contacto','registrar_datos_contacto','emitir_llamamiento','recuperar_llamamiento') OR p_ruta_clase NOT IN('coleccion','detalle','situacion','contactos','datos_contacto','emisiones') OR (p_actor_ref IS NOT NULL AND p_actor_ref !~ '^per_[A-Za-z0-9_-]{22,128}$') OR p_resultado NOT IN('autenticacion_requerida','acceso_denegado','recurso_no_disponible','infraestructura_no_disponible','resultado_indeterminado','correcto') THEN RAISE EXCEPTION 'intento de frontera Bolsa inválido' USING ERRCODE='22023'; END IF;
 v_ref:='intento:'||translate(encode(sha256(convert_to(p_correlacion_ref||':'||p_accion||':'||p_ruta_clase||':'||coalesce(p_actor_ref,'')||':'||p_resultado||':'||clock_timestamp()::text,'UTF8')),'hex'),'0123456789','ghijklmnop');
 INSERT INTO vec_bolsa_llamamientos.bitacora_intento_borrador_llamamiento(intento_ref,correlacion_ref,accion,ruta_clase,actor_ref,resultado,registrada_en) VALUES(v_ref,p_correlacion_ref,p_accion,p_ruta_clase,p_actor_ref,p_resultado,clock_timestamp());
END $f$;
ALTER TABLE vec_bolsa_llamamientos.contacto_participacion DROP CONSTRAINT contacto_participacion_resultado_check;
ALTER TABLE vec_bolsa_llamamientos.contacto_participacion ADD CONSTRAINT contacto_participacion_resultado_check CHECK(resultado IN('contactado','no_contesta','buzon','acepta','rechaza','aplazado','otro','enviado','no_enviado'));
CREATE TABLE vec_bolsa_llamamientos.llamamiento_emitido(
 llamamiento_ref text PRIMARY KEY,
 recibo_ref text NOT NULL UNIQUE,
 bolsa_ref text NOT NULL,
 actor_ref text NOT NULL,
 clave_idempotencia text NOT NULL,
 participaciones jsonb NOT NULL,
 configuracion jsonb NOT NULL,
	 huella_comando_sha256 text NOT NULL,
	 huella_finalizacion bytea NOT NULL CHECK(octet_length(huella_finalizacion)=32),
 estado text NOT NULL CHECK(estado='emision_reservada'),
 emitido_en timestamptz(6) NOT NULL,
 decision_ref text NOT NULL UNIQUE,
 UNIQUE(bolsa_ref,clave_idempotencia),
 CHECK(llamamiento_ref ~ '^llamamiento:[0-9a-f]{64}$' AND recibo_ref ~ '^recibo:llamamiento:[0-9a-f]{64}$'),
 CHECK(actor_ref ~ '^per_[A-Za-z0-9_-]{22,128}$'),
 CHECK(jsonb_typeof(participaciones)='array' AND jsonb_array_length(participaciones) BETWEEN 1 AND 100),
 CHECK(jsonb_typeof(configuracion)='object'),
 CHECK(huella_comando_sha256 ~ '^[0-9a-f]{64}$')
);
ALTER TABLE vec_bolsa_llamamientos.llamamiento_emitido ENABLE ROW LEVEL SECURITY;
ALTER TABLE vec_bolsa_llamamientos.llamamiento_emitido FORCE ROW LEVEL SECURITY;
CREATE POLICY llamamiento_emitido_solo_propietario ON vec_bolsa_llamamientos.llamamiento_emitido TO vec_bolsa_llamamientos_propietario USING(current_user='vec_bolsa_llamamientos_propietario') WITH CHECK(current_user='vec_bolsa_llamamientos_propietario');
REVOKE ALL ON vec_bolsa_llamamientos.llamamiento_emitido FROM PUBLIC;
CREATE TRIGGER llamamiento_emitido_inmutable BEFORE UPDATE OR DELETE ON vec_bolsa_llamamientos.llamamiento_emitido FOR EACH ROW EXECUTE FUNCTION vec_bolsa_llamamientos.constitucion_rechazar_mutacion();
CREATE FUNCTION vec_bolsa_llamamientos.reservar_llamamiento_v1(p_llamamiento text,p_recibo text,p_bolsa text,p_actor text,p_clave text,p_participaciones jsonb,p_configuracion jsonb,p_emitido timestamptz,p_huella_finalizacion bytea,p_capacidad bytea,p_decision bytea,p_motivo bytea,p_contexto bytea,p_persona_version numeric,p_perfil_version numeric,p_payload bytea,p_sobre bytea,p_evidencia bytea,p_raiz bytea)
RETURNS TABLE(emision jsonb,reutilizada boolean) LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog SET lock_timeout='2s' AS $f$
DECLARE previo record; consumo record; d jsonb; v_huella text; v_total int; v_validas int; v_ordenadas int; v_contactos jsonb; BEGIN
 IF current_user<>'vec_bolsa_llamamientos_propietario' OR p_llamamiento !~ '^llamamiento:[0-9a-f]{64}$' OR p_recibo !~ '^recibo:llamamiento:[0-9a-f]{64}$' OR p_actor !~ '^per_[A-Za-z0-9_-]{22,128}$' OR p_clave IS NULL OR p_clave<>btrim(p_clave) OR octet_length(p_clave) NOT BETWEEN 8 AND 256 OR jsonb_typeof(p_participaciones)<>'array' OR jsonb_array_length(p_participaciones) NOT BETWEEN 1 AND 100 OR NOT(SELECT bool_and(jsonb_typeof(value)='string') FROM jsonb_array_elements(p_participaciones)) OR jsonb_typeof(p_configuracion)<>'object' OR p_configuracion ?& ARRAY['referencia','descripcion','categoria','centro','modalidad','fecha_inicio','plazo','plantilla_version','asunto','cuerpo'] IS NOT TRUE OR NOT(SELECT count(*)=10 AND bool_and(jsonb_typeof(value)='string' AND octet_length(value#>>'{}') BETWEEN 2 AND 4000 AND value#>>'{}'=btrim(value#>>'{}')) FROM jsonb_each(p_configuracion)) OR p_configuracion->>'plantilla_version'<>'bolsa-llamamiento-v1' OR octet_length(p_huella_finalizacion) IS DISTINCT FROM 32 OR p_emitido IS NULL THEN RAISE EXCEPTION 'emisión B7 inválida' USING ERRCODE='22023'; END IF;
 v_huella:=encode(sha256(convert_to(p_bolsa||chr(31)||p_participaciones::text||chr(31)||p_configuracion::text,'UTF8')),'hex');
 PERFORM pg_advisory_xact_lock(hashtextextended('vec_bolsa_llamamientos:emision:'||p_bolsa||':'||p_clave,0));
 SELECT * INTO previo FROM vec_bolsa_llamamientos.llamamiento_emitido WHERE bolsa_ref=p_bolsa AND clave_idempotencia=p_clave;
 IF FOUND THEN
  IF previo.actor_ref<>p_actor OR previo.huella_comando_sha256<>v_huella THEN RAISE EXCEPTION 'clave B7 divergente' USING ERRCODE='VBE01'; END IF;
  SELECT coalesce(jsonb_agg(jsonb_build_object('participacion_ref',c.participacion_ref,'resultado',c.resultado,'recibo_ref',c.recibo_ref) ORDER BY x.ordinality),'[]'::jsonb) INTO v_contactos FROM jsonb_array_elements_text(previo.participaciones) WITH ORDINALITY x(ref,ordinality) JOIN vec_bolsa_llamamientos.contacto_participacion c ON c.participacion_ref=x.ref AND c.llamamiento_ref=previo.llamamiento_ref AND c.canal='correo' AND c.clave_idempotencia=previo.clave_idempotencia||':correo:'||x.ordinality AND c.recibo_ref='recibo:contacto:'||encode(sha256(convert_to(previo.bolsa_ref||chr(31)||previo.clave_idempotencia||chr(31)||x.ref,'UTF8')),'hex');
  RETURN QUERY SELECT jsonb_build_object('llamamiento_ref',previo.llamamiento_ref,'recibo_ref',previo.recibo_ref,'bolsa_ref',previo.bolsa_ref,'estado',CASE WHEN jsonb_array_length(v_contactos)=jsonb_array_length(previo.participaciones) THEN 'emitido_pendiente_respuesta' ELSE 'emision_reservada_resultado_pendiente' END,'participaciones',previo.participaciones,'configuracion',previo.configuracion,'emitido_en',previo.emitido_en,'contactos',v_contactos),true; RETURN;
 END IF;
 SELECT * INTO STRICT consumo FROM vec_autorizacion_atestada_v3.registrar_y_consumir_emision_llamamiento_v3_atestada(p_capacidad,p_decision,p_motivo,p_contexto,p_persona_version,p_perfil_version,p_payload,p_sobre,p_evidencia,p_raiz);
 BEGIN d:=convert_from(p_decision,'UTF8')::jsonb; EXCEPTION WHEN others THEN RAISE EXCEPTION 'decisión B7 inválida' USING ERRCODE='42501'; END;
 IF consumo.efecto_ref IS DISTINCT FROM p_bolsa OR consumo.consumo_nuevo IS NOT TRUE OR d->>'principal_id' IS DISTINCT FROM p_actor OR d->>'accion' IS DISTINCT FROM 'llamamiento.emitir.v1' OR d->>'tipo_recurso' IS DISTINCT FROM 'bolsa_constituida' THEN RAISE EXCEPTION 'emisión B7 no autorizada' USING ERRCODE='42501'; END IF;
 IF NOT EXISTS(SELECT 1 FROM vec_bolsa_llamamientos.constitucion c JOIN vec_bolsa_llamamientos.bolsa_constituida b ON b.bolsa_ref=c.bolsa_ref AND b.version=c.version_bolsa WHERE c.bolsa_ref=p_bolsa AND b.estado='vigente' AND b.vigente_desde<=p_emitido AND (b.vigente_hasta IS NULL OR p_emitido<b.vigente_hasta)) THEN RAISE EXCEPTION 'bolsa no vigente' USING ERRCODE='23503'; END IF;
 v_total:=jsonb_array_length(p_participaciones);
 SELECT count(*) INTO v_validas FROM jsonb_array_elements_text(p_participaciones) x(ref) JOIN vec_bolsa_llamamientos.constitucion c ON c.bolsa_ref=p_bolsa JOIN vec_bolsa_llamamientos.constitucion_entrada e ON e.instantanea_ref=c.instantanea_ref AND e.version_instantanea=c.version_instantanea AND e.participacion_ref=x.ref;
 SELECT count(*) INTO v_ordenadas FROM (SELECT e.orden,lag(e.orden) OVER(ORDER BY x.n) anterior FROM jsonb_array_elements_text(p_participaciones) WITH ORDINALITY x(ref,n) JOIN vec_bolsa_llamamientos.constitucion c ON c.bolsa_ref=p_bolsa JOIN vec_bolsa_llamamientos.constitucion_entrada e ON e.instantanea_ref=c.instantanea_ref AND e.version_instantanea=c.version_instantanea AND e.participacion_ref=x.ref) q WHERE anterior IS NULL OR orden>anterior;
 IF v_validas<>v_total OR v_ordenadas<>v_total OR (SELECT count(DISTINCT value) FROM jsonb_array_elements_text(p_participaciones))<>v_total THEN RAISE EXCEPTION 'participaciones ajenas, repetidas o desordenadas' USING ERRCODE='22023'; END IF;
 INSERT INTO vec_bolsa_llamamientos.llamamiento_emitido(llamamiento_ref,recibo_ref,bolsa_ref,actor_ref,clave_idempotencia,participaciones,configuracion,huella_comando_sha256,huella_finalizacion,estado,emitido_en,decision_ref) VALUES(p_llamamiento,p_recibo,p_bolsa,p_actor,p_clave,p_participaciones,p_configuracion,v_huella,p_huella_finalizacion,'emision_reservada',p_emitido,consumo.decision_ref);
 RETURN QUERY SELECT jsonb_build_object('llamamiento_ref',p_llamamiento,'recibo_ref',p_recibo,'bolsa_ref',p_bolsa,'estado','emision_reservada_resultado_pendiente','participaciones',p_participaciones,'configuracion',p_configuracion,'emitido_en',p_emitido,'contactos','[]'::jsonb),false;
END $f$;
CREATE FUNCTION vec_bolsa_llamamientos.registrar_contactos_llamamiento_v1(p_bolsa text,p_clave text,p_actor text,p_token_finalizacion bytea,p_contactos jsonb) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog SET lock_timeout='2s' AS $f$
DECLARE previo record; v_contactos jsonb; BEGIN
 IF current_user<>'vec_bolsa_llamamientos_propietario' OR p_actor !~ '^per_[A-Za-z0-9_-]{22,128}$' OR jsonb_typeof(p_contactos)<>'array' THEN RAISE EXCEPTION 'resultado B7 inválido' USING ERRCODE='22023'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended('vec_bolsa_llamamientos:emision:'||p_bolsa||':'||p_clave,0));
 SELECT * INTO previo FROM vec_bolsa_llamamientos.llamamiento_emitido WHERE bolsa_ref=p_bolsa AND clave_idempotencia=p_clave;
 IF NOT FOUND OR previo.actor_ref<>p_actor OR octet_length(p_token_finalizacion) IS DISTINCT FROM 32 OR previo.huella_finalizacion IS DISTINCT FROM sha256(p_token_finalizacion) OR jsonb_array_length(p_contactos)<>jsonb_array_length(previo.participaciones) OR NOT(SELECT bool_and(jsonb_typeof(c.value)='object' AND (SELECT count(*)=3 FROM jsonb_object_keys(c.value)) AND c.value->>'participacion_ref'=previo.participaciones->>(c.ordinality-1)::int AND c.value->>'resultado' IN('enviado','no_enviado') AND c.value->>'recibo_ref'='recibo:contacto:'||encode(sha256(convert_to(previo.bolsa_ref||chr(31)||previo.clave_idempotencia||chr(31)||(c.value->>'participacion_ref'),'UTF8')),'hex')) FROM jsonb_array_elements(p_contactos) WITH ORDINALITY c(value,ordinality)) THEN RAISE EXCEPTION 'resultado B7 no autorizado' USING ERRCODE='42501'; END IF;
 SELECT coalesce(jsonb_agg(jsonb_build_object('participacion_ref',c.participacion_ref,'resultado',c.resultado,'recibo_ref',c.recibo_ref) ORDER BY x.ordinality),'[]'::jsonb) INTO v_contactos FROM jsonb_array_elements_text(previo.participaciones) WITH ORDINALITY x(ref,ordinality) JOIN vec_bolsa_llamamientos.contacto_participacion c ON c.participacion_ref=x.ref AND c.llamamiento_ref=previo.llamamiento_ref AND c.canal='correo' AND c.clave_idempotencia=previo.clave_idempotencia||':correo:'||x.ordinality AND c.recibo_ref='recibo:contacto:'||encode(sha256(convert_to(previo.bolsa_ref||chr(31)||previo.clave_idempotencia||chr(31)||x.ref,'UTF8')),'hex');
 IF jsonb_array_length(v_contactos)=jsonb_array_length(previo.participaciones) THEN RETURN jsonb_build_object('llamamiento_ref',previo.llamamiento_ref,'recibo_ref',previo.recibo_ref,'bolsa_ref',previo.bolsa_ref,'estado','emitido_pendiente_respuesta','participaciones',previo.participaciones,'configuracion',previo.configuracion,'emitido_en',previo.emitido_en,'contactos',v_contactos); END IF;
 IF jsonb_array_length(v_contactos)<>0 THEN RAISE EXCEPTION 'resultado B7 parcial' USING ERRCODE='55000'; END IF;
 INSERT INTO vec_bolsa_llamamientos.contacto_participacion(contacto_ref,bolsa_ref,participacion_ref,llamamiento_ref,canal,instante,actor,resultado,anotacion,clave_idempotencia,recibo_ref)
 SELECT 'contacto:'||encode(sha256(convert_to(p_bolsa||chr(31)||p_clave||chr(31)||(c.value->>'participacion_ref'),'UTF8')),'hex'),p_bolsa,c.value->>'participacion_ref',previo.llamamiento_ref,'correo',previo.emitido_en,p_actor,c.value->>'resultado','Emisión de llamamiento por plantilla '||(previo.configuracion->>'plantilla_version'),p_clave||':correo:'||c.ordinality,c.value->>'recibo_ref' FROM jsonb_array_elements(p_contactos) WITH ORDINALITY c(value,ordinality);
 RETURN jsonb_build_object('llamamiento_ref',previo.llamamiento_ref,'recibo_ref',previo.recibo_ref,'bolsa_ref',previo.bolsa_ref,'estado','emitido_pendiente_respuesta','participaciones',previo.participaciones,'configuracion',previo.configuracion,'emitido_en',previo.emitido_en,'contactos',p_contactos);
END $f$;
CREATE FUNCTION vec_bolsa_llamamientos.recuperar_llamamiento_emitido_v1(p_bolsa text,p_clave text) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $f$
 SELECT jsonb_build_object('llamamiento_ref',l.llamamiento_ref,'recibo_ref',l.recibo_ref,'bolsa_ref',l.bolsa_ref,'estado',CASE WHEN (SELECT count(*) FROM jsonb_array_elements_text(l.participaciones) WITH ORDINALITY x(ref,ordinality) JOIN vec_bolsa_llamamientos.contacto_participacion c ON c.participacion_ref=x.ref AND c.llamamiento_ref=l.llamamiento_ref AND c.canal='correo' AND c.clave_idempotencia=l.clave_idempotencia||':correo:'||x.ordinality AND c.recibo_ref='recibo:contacto:'||encode(sha256(convert_to(l.bolsa_ref||chr(31)||l.clave_idempotencia||chr(31)||x.ref,'UTF8')),'hex'))=jsonb_array_length(l.participaciones) THEN 'emitido_pendiente_respuesta' ELSE 'emision_reservada_resultado_pendiente' END,'participaciones',l.participaciones,'configuracion',l.configuracion,'emitido_en',l.emitido_en,'contactos',coalesce((SELECT jsonb_agg(jsonb_build_object('participacion_ref',c.participacion_ref,'resultado',c.resultado,'recibo_ref',c.recibo_ref) ORDER BY x.ordinality) FROM jsonb_array_elements_text(l.participaciones) WITH ORDINALITY x(ref,ordinality) JOIN vec_bolsa_llamamientos.contacto_participacion c ON c.participacion_ref=x.ref AND c.llamamiento_ref=l.llamamiento_ref AND c.canal='correo' AND c.clave_idempotencia=l.clave_idempotencia||':correo:'||x.ordinality AND c.recibo_ref='recibo:contacto:'||encode(sha256(convert_to(l.bolsa_ref||chr(31)||l.clave_idempotencia||chr(31)||x.ref,'UTF8')),'hex')),'[]'::jsonb)) FROM vec_bolsa_llamamientos.llamamiento_emitido l WHERE l.bolsa_ref=p_bolsa AND l.clave_idempotencia=p_clave
$f$;
CREATE FUNCTION vec_bolsa_llamamientos.contar_llamamientos_en_curso_v1(p_bolsa text) RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $f$ SELECT count(*) FROM vec_bolsa_llamamientos.llamamiento_emitido l WHERE l.bolsa_ref=p_bolsa AND (SELECT count(*) FROM jsonb_array_elements_text(l.participaciones) WITH ORDINALITY x(ref,ordinality) JOIN vec_bolsa_llamamientos.contacto_participacion c ON c.participacion_ref=x.ref AND c.llamamiento_ref=l.llamamiento_ref AND c.canal='correo' AND c.clave_idempotencia=l.clave_idempotencia||':correo:'||x.ordinality AND c.recibo_ref='recibo:contacto:'||encode(sha256(convert_to(l.bolsa_ref||chr(31)||l.clave_idempotencia||chr(31)||x.ref,'UTF8')),'hex'))=jsonb_array_length(l.participaciones) $f$;
REVOKE ALL ON FUNCTION vec_bolsa_llamamientos.reservar_llamamiento_v1(text,text,text,text,text,jsonb,jsonb,timestamptz,bytea,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea),vec_bolsa_llamamientos.registrar_contactos_llamamiento_v1(text,text,text,bytea,jsonb),vec_bolsa_llamamientos.recuperar_llamamiento_emitido_v1(text,text),vec_bolsa_llamamientos.contar_llamamientos_en_curso_v1(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION vec_bolsa_llamamientos.reservar_llamamiento_v1(text,text,text,text,text,jsonb,jsonb,timestamptz,bytea,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea),vec_bolsa_llamamientos.registrar_contactos_llamamiento_v1(text,text,text,bytea,jsonb),vec_bolsa_llamamientos.recuperar_llamamiento_emitido_v1(text,text),vec_bolsa_llamamientos.contar_llamamientos_en_curso_v1(text) TO vec_bolsa_llamamientos_ejecutor;
COMMIT;
