\set ON_ERROR_STOP on
-- B65: cierra la búsqueda de tipos de la clausura externa.
-- Conserva cuerpos, firmas, OID, propietarios, ACL, canon e historia.
-- Requiere B60/B61. No reaplicar sobre una instalación ya corregida.
BEGIN;
SET LOCAL search_path=pg_catalog,pg_temp;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='60s';
SELECT pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('bolsa_llamamientos:migracion:externa:000065',0));
DO $correctiva$
DECLARE esperado record; antes record; despues record; acl_actual pg_catalog.jsonb;
BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_catalog.pg_roles WHERE rolname=current_user AND rolsuper)
    OR pg_catalog.current_setting('transaction_isolation')<>'read committed'
    OR pg_catalog.to_regrole('vec_bolsa_llamamientos_propietario') IS NULL THEN
  RAISE EXCEPTION 'B65: migrador no autorizado' USING ERRCODE='55000';
 END IF;
 FOR esperado IN SELECT * FROM (VALUES
  ('vec_bolsa_llamamientos.anotar_consumo_candidato_v1(text,text,text)','e3e571f0dfdfe0ae6d88b4639701df20db99c4c474c1f35ed6c72a9d2a85031f',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.confirmar_contacto_propio_v1(text,text,bigint,text,text,timestamp with time zone,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)','2e464dc67485d466b2fe964bbfa8cefd868cee4187cfbb820a1756e7ec68f497',true,'["search_path=pg_catalog", "TimeZone=UTC", "lock_timeout=2s"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_ejecutor", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_portal_externo", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.consultar_historial_mi_bolsa_v1(text,timestamp with time zone,integer,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)','86e484771e7ebe1e9beb8643ac96dd73e0b62c6ee4782dc65072a4f1cbf999c9',true,'["search_path=pg_catalog", "lock_timeout=2s", "statement_timeout=15s"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_ejecutor", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_portal_externo", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.consultar_mi_bolsa_portal_v1(text,timestamp with time zone,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)','d626cad864b5758498e93ace3788774e205640565d21b1dd257933a04b7c01b1',true,'["search_path=pg_catalog", "lock_timeout=2s"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_ejecutor", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_portal_externo", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.consultar_mi_bolsa_v1(text,timestamp with time zone,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)','ded995d98d206749aae198b3e15d13c38624c6732b426ac24f8fdb07d717d12b',true,'["search_path=pg_catalog", "lock_timeout=2s", "statement_timeout=15s"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_ejecutor", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_portal_externo", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.estado_cese_bolsa_v1(text,timestamp with time zone)','d723bc97c35b12e30deae4bc8ed3ef2a343aae526a03b6db6542470b732104bf',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.exigir_consumo_candidato_v1(text[],text)','534e39587b13c0068291e895216c0121ebe380b05c5763a81c59493b8c104fbc',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.exigir_portal_candidato_v1(text,text,text,bytea,bytea,bytea)','da597bb760b6e2ca54379f5e06e389a1abec8744b24de4c8025fbce3002d8f9a',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.firma_marca_consumo_v1(xid8,text,text,text)','0f409adce64d85ed7b457b010b94559ba0b4b50367935ea224df674f3646b6be',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.leer_contacto_candidato_v1(text,timestamp with time zone)','9deeea99249543b918999cbc4b9526c2d1ff982ca732b12cb86ff75810e80e7a',true,'["search_path=pg_catalog", "TimeZone=UTC"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_ejecutor", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_portal_externo", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.leer_orden_vigente_bolsa_v1(text,timestamp with time zone)','049d15c58525a8f326b67801c06a8a63fdf27d19f5000fefb348b0da260ae0e2',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_ejecutor", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.leer_portal_candidato_v1(text,timestamp with time zone,text[])','d85901d905d46537709708d7a6c96bd9b4d7f3899e3af3e5e2c266ef51bb7755',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_ejecutor", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_portal_externo", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.listar_ofertas_candidato_v1(text,timestamp with time zone)','c571a95d1e617819930a5a0ba48011b6f971f484ed7bdc9c10d153ee79f46028',true,'["search_path=pg_catalog", "TimeZone=UTC"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_ejecutor", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_portal_externo", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.listar_participaciones_candidato_v1(text)','9997743780a837b4c611f8fdbcf1ba26b52eb36cb9f9c379a1dfb027b0987e6f',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.llamamiento_abierto_portal_v1(text,timestamp with time zone,text[])','c6c98bf38a5dcfe73557de0c32dcb9ee81ec779983dc421badbd55841ec15f06',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.manifestar_disposicion_oferta_v1(text,text,text,text,timestamp with time zone,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)','29998a71df14ee29428ac324ad72aa5389c353b57904462d1e99ccf56334359e',true,'["search_path=pg_catalog", "TimeZone=UTC", "lock_timeout=2s"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_ejecutor", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_portal_externo", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.participacion_contacto_candidato_v1(text,text)','140db1a981e828d605f2e8fc64f35d564b08a568ea24d104bba92c2ee7090d70',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.participacion_oferta_candidato_v1(text,text)','f57ccd918f6b9e2a1c9c6a20be35f2b3236dd00a5400cd48445d11cc37ec12cc',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.participacion_portal_candidato_v1(text,text)','615fece0c09cb941abe93d22bde6e05682bd4fbdd9c903649a251bb172190c7c',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.participaciones_vigentes_candidato_v1(text)','38594738350993026e437f9064292563e03d4273d60925e42d6dd9291598696c',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.preparar_respuesta_portal_v1(text,text,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)','5b896bbc3be02068a9efea73f9382ca37e5979d5751fdd83b5d91aa3a3fbe586',true,'["search_path=pg_catalog", "lock_timeout=2s"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_ejecutor", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_portal_externo", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.proyectar_oferta_v1(text,timestamp with time zone)','8eeace70e62dce54c6538f935845c7e89f03981f8cb47bf4fbe8c40b94d3cc8f',true,'["search_path=pg_catalog", "TimeZone=UTC"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.proyectar_oferta_v2(text,timestamp with time zone)','e3c0a46fca8daed88fe7949910710b88ff5eb967376402143092ae37fc6dfc15',true,'["search_path=pg_catalog", "TimeZone=UTC"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.registrar_confirmacion_contacto_interna_v1(text,text,text,bigint,text,text,timestamp with time zone,text)','a58d9b9cd6a0c9e20b9fd4d3c4b779093d08b320f545cf6c10140043875d64bf',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.registrar_disposicion_oferta_interna_v1(text,text,text,text,text,timestamp with time zone,text)','21b22dac12277a6463c06d77f074aec2a88d715a5592afa88b4570879b1f9d41',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.registrar_respuesta_portal_interna_v1(text,text,text,text,text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,text[],text,text,timestamp with time zone,text)','5e675b8ad2662dd3d0a81cde94c30d5013fd1574ebe2ee36aa9f8e71e2f4b102',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.registrar_solicitud_portal_interna_v1(text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,text[],text,text,timestamp with time zone,text)','93c6793321f509bcf23e34f1c2aec0dfb56b9682e65fa5e89451242a9fa6c476',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.responder_llamamiento_portal_v1(text,text,text,text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,text[],text,text,timestamp with time zone,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)','b5d47c6df5facc2bb704fc2ecb2fb096825c46f4c23790bd9582ef9a8eb35c03',true,'["search_path=pg_catalog", "lock_timeout=2s"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_ejecutor", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_portal_externo", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.solicitar_portal_candidato_v1(text,text,text,text,text,timestamp with time zone,timestamp with time zone,text[],text,text,timestamp with time zone,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)','a1d8bf50f4eebfda08514a7d12c1c98da477ad42258fda5bdb745b61fe09e2ab',true,'["search_path=pg_catalog", "lock_timeout=2s"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_ejecutor", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_portal_externo", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}, {"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb),
  ('vec_bolsa_llamamientos.solicitud_portal_pendiente_v1(text)','66cd081efbec9a3bf86c1fb0d2b0090a1529b9694c8ff80c114f860acf530e6d',true,'["search_path=pg_catalog"]'::jsonb,'[{"grantee": "vec_bolsa_llamamientos_propietario", "grantor": "vec_bolsa_llamamientos_propietario", "grantable": false, "privilege": "EXECUTE"}]'::jsonb)
 ) AS inventario(firma,huella,definidor,configuracion,acl) LOOP
  SELECT p.* INTO antes FROM pg_catalog.pg_proc p WHERE p.oid=pg_catalog.to_regprocedure(esperado.firma);
  IF NOT FOUND THEN RAISE EXCEPTION 'B65: preimagen incompatible para %',esperado.firma USING ERRCODE='55000'; END IF;
  SELECT coalesce(pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object(
    'grantee',r.rolname,'grantor',g.rolname,'grantable',a.is_grantable,'privilege',a.privilege_type)
    ORDER BY r.rolname,g.rolname,a.privilege_type,a.is_grantable),'[]'::pg_catalog.jsonb)
  INTO acl_actual FROM pg_catalog.aclexplode(coalesce(antes.proacl,pg_catalog.acldefault('f',antes.proowner))) a
  LEFT JOIN pg_catalog.pg_roles r ON r.oid=a.grantee LEFT JOIN pg_catalog.pg_roles g ON g.oid=a.grantor;
  IF antes.proowner IS DISTINCT FROM pg_catalog.to_regrole('vec_bolsa_llamamientos_propietario')
     OR antes.prosecdef IS DISTINCT FROM esperado.definidor
     OR pg_catalog.to_jsonb(antes.proconfig) IS DISTINCT FROM esperado.configuracion
     OR pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(antes.prosrc,'UTF8')),'hex') IS DISTINCT FROM esperado.huella
     OR acl_actual IS DISTINCT FROM esperado.acl THEN
   RAISE EXCEPTION 'B65: preimagen incompatible para %',esperado.firma USING ERRCODE='55000';
  END IF;
  EXECUTE pg_catalog.format('ALTER FUNCTION %s SET search_path=pg_catalog,pg_temp',antes.oid::pg_catalog.regprocedure);
  SELECT p.* INTO STRICT despues FROM pg_catalog.pg_proc p WHERE p.oid=antes.oid;
  IF pg_catalog.to_jsonb(despues)-'proconfig' IS DISTINCT FROM pg_catalog.to_jsonb(antes)-'proconfig'
     OR (SELECT pg_catalog.array_agg(CASE WHEN opcion='search_path=pg_catalog' THEN 'search_path=pg_catalog, pg_temp' ELSE opcion END ORDER BY indice)
         FROM pg_catalog.unnest(antes.proconfig) WITH ORDINALITY AS opciones(opcion,indice)) IS DISTINCT FROM despues.proconfig THEN
   RAISE EXCEPTION 'B65: postimagen incompatible para %',esperado.firma USING ERRCODE='55000';
  END IF;
 END LOOP;
END $correctiva$;
COMMIT;
