\set ON_ERROR_STOP on
-- AD3-133: convergencia forward post-AD118/AUT21/AD134/AD136 de dos linajes completos.
-- Sustituye AD3-121/122: no registra esas migraciones como ejecutadas.
-- Requiere después AD3-135 (sustitución de AD3-123), AD3-124, D11 y U15.
-- Conserva prosrc, las ramas AD111/114, RPT y E3, OID, owner, ACL, dependencias e historia.
-- Solo cambia search_path. Deniega mezclas, preimágenes ajenas y reaplicación.
-- Matrices sintéticas PG18 post118/AUT21/134/136: ampliada ac7d03ff9b86ddf01ca03d8dc286532c87c7ce0f62abba44cd47c828ba9a8704;
-- copias externas históricas con núcleo completo b966879c7c23420ad27c7faa85be458f18f8b79ea90efae52e6aaa1fa088db98.
BEGIN;
SET LOCAL search_path=pg_catalog,pg_temp;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='60s';
SELECT pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('vec_autorizacion_atestada_v3:migracion:000118',0));
SELECT pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('vec_autorizacion_atestada_v3:nucleo',0));
SELECT pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('autorizacion_atestada_v3:migracion:externa:000121',0));
SELECT pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('autorizacion_atestada_v3:migracion:externa:000122',0));
SELECT pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('vec_autorizacion_atestada_v3:migracion:000133',0));
DO $convergencia$
DECLARE
 ampliada pg_catalog.jsonb := $matriz$[
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":null,"argtypes":["bytea","bytea"],"firma":"vec_autorizacion_atestada_v3.bytea_igual_constante(bytea,bytea)","language":"plpgsql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_language","refobjsubid":0,"target":{"identity":"plpgsql","name":"plpgsql","schema":null,"type":"language"}},{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":null,"proargnames":["p_primero","p_segundo"],"probin":null,"proconfig":["search_path=pg_catalog"],"procost":100,"proisstrict":true,"prokind":"f","proleakproof":false,"proname":"bytea_igual_constante","pronargdefaults":0,"pronargs":2,"proparallel":"u","proretset":false,"prorows":0,"prosecdef":false,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"i"},"pg_shdepend":[{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"boolean","sha_prosrc":"6064e75af36ba6593c1746d59eb690a4d1fc2ce51d451428a495b6f16e0f2183","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":null,"argtypes":["jsonb"],"firma":"vec_autorizacion_atestada_v3.capacidad_canonica(jsonb)","language":"sql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":null,"proargnames":["c"],"probin":null,"proconfig":["search_path=pg_catalog"],"procost":100,"proisstrict":true,"prokind":"f","proleakproof":false,"proname":"capacidad_canonica","pronargdefaults":0,"pronargs":1,"proparallel":"u","proretset":false,"prorows":0,"prosecdef":false,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"i"},"pg_shdepend":[{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"bytea","sha_prosrc":"aa7ba0652224c93fc4d1f0bec46049aac24e93b7abdd4955eebb718be0527fd8","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":null,"argtypes":["bytea"],"firma":"vec_autorizacion_atestada_v3.capacidad_cruda_prevalida(bytea)","language":"plpgsql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_language","refobjsubid":0,"target":{"identity":"plpgsql","name":"plpgsql","schema":null,"type":"language"}},{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":null,"proargnames":["p_capacidad"],"probin":null,"proconfig":["search_path=pg_catalog"],"procost":100,"proisstrict":false,"prokind":"f","proleakproof":false,"proname":"capacidad_cruda_prevalida","pronargdefaults":0,"pronargs":1,"proparallel":"u","proretset":false,"prorows":0,"prosecdef":false,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"i"},"pg_shdepend":[{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"boolean","sha_prosrc":"2c44c59293746b836647a9922c5fbb833ce1aae7e42a9ecfe7c8ab659263acb6","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":null,"argtypes":["jsonb"],"firma":"vec_autorizacion_atestada_v3.capacidad_tipos_validos(jsonb)","language":"sql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":null,"proargnames":["c"],"probin":null,"proconfig":["search_path=pg_catalog"],"procost":100,"proisstrict":true,"prokind":"f","proleakproof":false,"proname":"capacidad_tipos_validos","pronargdefaults":0,"pronargs":1,"proparallel":"u","proretset":false,"prorows":0,"prosecdef":false,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"i"},"pg_shdepend":[{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"boolean","sha_prosrc":"b9c331a9cbd635abc8325e9233bcabd38a3bc10215c0cc49929871f22410c669","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_preflight_externo","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"},{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":null,"argtypes":["text","jsonb"],"firma":"vec_autorizacion_atestada_v3.comprobar_material_emision_externa_v1(text,jsonb)","language":"plpgsql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_language","refobjsubid":0,"target":{"identity":"plpgsql","name":"plpgsql","schema":null,"type":"language"}},{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":null,"proargnames":["p_consumidor","p_material"],"probin":null,"proconfig":["search_path=pg_catalog","lock_timeout=2s"],"procost":100,"proisstrict":false,"prokind":"f","proleakproof":false,"proname":"comprobar_material_emision_externa_v1","pronargdefaults":0,"pronargs":2,"proparallel":"u","proretset":false,"prorows":0,"prosecdef":true,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"s"},"pg_shdepend":[{"class":"pg_proc","deptype":"a","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_preflight_externo","name":"vec_autorizacion_atestada_v3_preflight_externo","schema":null,"type":"role"}},{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"boolean","sha_prosrc":"0ba180fec6ecd5328ab084e2b2e1cf3ec8f8cefec1fd603cf176e9741c5832e7","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":["text","bytea","bytea","bytea","bytea","numeric","numeric","bytea","bytea","bytea","bytea","text","text","text","text","text","timestamp with time zone","boolean"],"argtypes":["text","bytea","bytea","bytea","bytea","numeric","numeric","bytea","bytea","bytea","bytea"],"firma":"vec_autorizacion_atestada_v3.consumir_decision_mutacion_v3_externa_interna(text,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)","language":"plpgsql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_language","refobjsubid":0,"target":{"identity":"plpgsql","name":"plpgsql","schema":null,"type":"language"}},{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":["i","i","i","i","i","i","i","i","i","i","i","t","t","t","t","t","t","t"],"proargnames":["p_perfil_mutacion","p_capacidad_canonica","p_decision_canonica","p_motivo_canonico","p_contexto_actor_canonico","p_persona_version","p_perfil_version","p_payload_vec_ad_3","p_sobre_cose_sign1","p_evidencia_verificacion","p_raiz_publica_spki","decision_ref","efecto_ref","huella_efecto_sha256","consumo_huella_sha256","auditoria_ref","consumida_en","consumo_nuevo"],"probin":null,"proconfig":["search_path=pg_catalog","lock_timeout=2s"],"procost":100,"proisstrict":false,"prokind":"f","proleakproof":false,"proname":"consumir_decision_mutacion_v3_externa_interna","pronargdefaults":0,"pronargs":11,"proparallel":"u","proretset":true,"prorows":1000,"prosecdef":true,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"v"},"pg_shdepend":[{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"record","sha_prosrc":"9cedce409c0e0e98f2be0a2d7dcd28c80be0316396c8fc58fc907d28f99a2ef2","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":["text","bytea","bytea","bytea","bytea","numeric","numeric","bytea","bytea","bytea","bytea","text","text","text","text","text","timestamp with time zone","boolean"],"argtypes":["text","bytea","bytea","bytea","bytea","numeric","numeric","bytea","bytea","bytea","bytea"],"firma":"vec_autorizacion_atestada_v3.consumir_decision_mutacion_v3_interna(text,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)","language":"plpgsql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_language","refobjsubid":0,"target":{"identity":"plpgsql","name":"plpgsql","schema":null,"type":"language"}},{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":["i","i","i","i","i","i","i","i","i","i","i","t","t","t","t","t","t","t"],"proargnames":["p_perfil_mutacion","p_capacidad_canonica","p_decision_canonica","p_motivo_canonico","p_contexto_actor_canonico","p_persona_version","p_perfil_version","p_payload_vec_ad_3","p_sobre_cose_sign1","p_evidencia_verificacion","p_raiz_publica_spki","decision_ref","efecto_ref","huella_efecto_sha256","consumo_huella_sha256","auditoria_ref","consumida_en","consumo_nuevo"],"probin":null,"proconfig":["search_path=pg_catalog","lock_timeout=2s"],"procost":100,"proisstrict":false,"prokind":"f","proleakproof":false,"proname":"consumir_decision_mutacion_v3_interna","pronargdefaults":0,"pronargs":11,"proparallel":"u","proretset":true,"prorows":1000,"prosecdef":true,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"v"},"pg_shdepend":[{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"record","sha_prosrc":"91f93a2695862b677c282ce6d0c4972148fe170e38540c8cfe3751f0ad5e4fb5","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":["text","bytea","bytea","bytea","bytea","numeric","numeric","bytea","bytea","bytea","bytea","text","text","text","text","text","timestamp with time zone","boolean"],"argtypes":["text","bytea","bytea","bytea","bytea","numeric","numeric","bytea","bytea","bytea","bytea"],"firma":"vec_autorizacion_atestada_v3.consumir_decision_mutacion_v3_usuarios_externa_interna(text,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)","language":"plpgsql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_language","refobjsubid":0,"target":{"identity":"plpgsql","name":"plpgsql","schema":null,"type":"language"}},{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":["i","i","i","i","i","i","i","i","i","i","i","t","t","t","t","t","t","t"],"proargnames":["p_perfil_mutacion","p_capacidad_canonica","p_decision_canonica","p_motivo_canonico","p_contexto_actor_canonico","p_persona_version","p_perfil_version","p_payload_vec_ad_3","p_sobre_cose_sign1","p_evidencia_verificacion","p_raiz_publica_spki","decision_ref","efecto_ref","huella_efecto_sha256","consumo_huella_sha256","auditoria_ref","consumida_en","consumo_nuevo"],"probin":null,"proconfig":["search_path=pg_catalog","lock_timeout=2s"],"procost":100,"proisstrict":false,"prokind":"f","proleakproof":false,"proname":"consumir_decision_mutacion_v3_usuarios_externa_interna","pronargdefaults":0,"pronargs":11,"proparallel":"u","proretset":true,"prorows":1000,"prosecdef":true,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"v"},"pg_shdepend":[{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"record","sha_prosrc":"c40f2f2dd68f6509f9c3861ebb9cfdc51e42407f6ea9eb1faa8cba3ac0c8fc98","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":null,"argtypes":["text"],"firma":"vec_autorizacion_atestada_v3.encuadrar_mac(text)","language":"sql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":null,"proargnames":["p_valor"],"probin":null,"proconfig":["search_path=pg_catalog"],"procost":100,"proisstrict":true,"prokind":"f","proleakproof":false,"proname":"encuadrar_mac","pronargdefaults":0,"pronargs":1,"proparallel":"u","proretset":false,"prorows":0,"prosecdef":false,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"i"},"pg_shdepend":[{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"bytea","sha_prosrc":"1d580fb6f1dd53f3c7a7933772a3d6649effb3ad10ffec42df534f8dab3ec69d","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":null,"argtypes":["text"],"firma":"vec_autorizacion_atestada_v3.huella_sha256_valida(text)","language":"sql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":null,"proargnames":["p_valor"],"probin":null,"proconfig":["search_path=pg_catalog"],"procost":100,"proisstrict":false,"prokind":"f","proleakproof":false,"proname":"huella_sha256_valida","pronargdefaults":0,"pronargs":1,"proparallel":"u","proretset":false,"prorows":0,"prosecdef":false,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"i"},"pg_shdepend":[{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"boolean","sha_prosrc":"003b525f9d89dd4faf913f17675cafe60479d8ab17c09cf746deb23bf310dfe8","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_preflight_externo","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"},{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":null,"argtypes":["text","jsonb"],"firma":"vec_autorizacion_atestada_v3.leer_configuracion_externa_v1(text,jsonb)","language":"plpgsql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_language","refobjsubid":0,"target":{"identity":"plpgsql","name":"plpgsql","schema":null,"type":"language"}},{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":null,"proargnames":["p_consumidor","p_material"],"probin":null,"proconfig":["search_path=pg_catalog","lock_timeout=2s"],"procost":100,"proisstrict":false,"prokind":"f","proleakproof":false,"proname":"leer_configuracion_externa_v1","pronargdefaults":0,"pronargs":2,"proparallel":"u","proretset":false,"prorows":0,"prosecdef":true,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"s"},"pg_shdepend":[{"class":"pg_proc","deptype":"a","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_preflight_externo","name":"vec_autorizacion_atestada_v3_preflight_externo","schema":null,"type":"role"}},{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"jsonb","sha_prosrc":"f64428afaf5871119ff7a6c8e04bdda98616ca4a151c6e2bd23dd308d37bb3ee","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":null,"argtypes":["jsonb"],"firma":"vec_autorizacion_atestada_v3.preimagen_mac(jsonb)","language":"sql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":null,"proargnames":["c"],"probin":null,"proconfig":["search_path=pg_catalog"],"procost":100,"proisstrict":true,"prokind":"f","proleakproof":false,"proname":"preimagen_mac","pronargdefaults":0,"pronargs":1,"proparallel":"u","proretset":false,"prorows":0,"prosecdef":false,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"i"},"pg_shdepend":[{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"bytea","sha_prosrc":"45a23c36c1d42bdb63e4cc2f7e72cb155dc6f779f021261815980adec7506418","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"},{"grantable":false,"grantee":"vec_bolsa_llamamientos_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":["bytea","bytea","bytea","bytea","numeric","numeric","bytea","bytea","bytea","bytea","text","text","text","text","text","timestamp with time zone","boolean"],"argtypes":["bytea","bytea","bytea","bytea","numeric","numeric","bytea","bytea","bytea","bytea"],"firma":"vec_autorizacion_atestada_v3.registrar_y_consumir_contacto_propio_bolsa_v3_atestada(bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)","language":"plpgsql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_language","refobjsubid":0,"target":{"identity":"plpgsql","name":"plpgsql","schema":null,"type":"language"}},{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":["i","i","i","i","i","i","i","i","i","i","t","t","t","t","t","t","t"],"proargnames":["p_capacidad","p_decision","p_motivo","p_contexto","p_persona_version","p_perfil_version","p_payload","p_sobre","p_evidencia","p_raiz","decision_ref","efecto_ref","huella_efecto_sha256","consumo_huella_sha256","auditoria_ref","consumida_en","consumo_nuevo"],"probin":null,"proconfig":["search_path=pg_catalog","lock_timeout=2s"],"procost":100,"proisstrict":false,"prokind":"f","proleakproof":false,"proname":"registrar_y_consumir_contacto_propio_bolsa_v3_atestada","pronargdefaults":0,"pronargs":10,"proparallel":"u","proretset":true,"prorows":1000,"prosecdef":true,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"v"},"pg_shdepend":[{"class":"pg_proc","deptype":"a","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_bolsa_llamamientos_propietario","name":"vec_bolsa_llamamientos_propietario","schema":null,"type":"role"}},{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"record","sha_prosrc":"3aff739498bbdf7c9313d5da5900ca60a9bd4637c2f396f583da815f9d040d56","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"},{"grantable":false,"grantee":"vec_bolsa_llamamientos_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":["bytea","bytea","bytea","bytea","numeric","numeric","bytea","bytea","bytea","bytea","text","text","text","text","text","timestamp with time zone","boolean"],"argtypes":["bytea","bytea","bytea","bytea","numeric","numeric","bytea","bytea","bytea","bytea"],"firma":"vec_autorizacion_atestada_v3.registrar_y_consumir_historial_propio_bolsa_v3_atestada(bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)","language":"plpgsql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_language","refobjsubid":0,"target":{"identity":"plpgsql","name":"plpgsql","schema":null,"type":"language"}},{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":["i","i","i","i","i","i","i","i","i","i","t","t","t","t","t","t","t"],"proargnames":["p_capacidad","p_decision","p_motivo","p_contexto","p_persona_version","p_perfil_version","p_payload","p_sobre","p_evidencia","p_raiz","decision_ref","efecto_ref","huella_efecto_sha256","consumo_huella_sha256","auditoria_ref","consumida_en","consumo_nuevo"],"probin":null,"proconfig":["search_path=pg_catalog","lock_timeout=2s"],"procost":100,"proisstrict":false,"prokind":"f","proleakproof":false,"proname":"registrar_y_consumir_historial_propio_bolsa_v3_atestada","pronargdefaults":0,"pronargs":10,"proparallel":"u","proretset":true,"prorows":1000,"prosecdef":true,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"v"},"pg_shdepend":[{"class":"pg_proc","deptype":"a","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_bolsa_llamamientos_propietario","name":"vec_bolsa_llamamientos_propietario","schema":null,"type":"role"}},{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"record","sha_prosrc":"8dfe36c0e95446e25a51e61abe45d6f97822527fd91d0314e41ec2fdb23be138","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"},{"grantable":false,"grantee":"vec_bolsa_llamamientos_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":["bytea","bytea","bytea","bytea","numeric","numeric","bytea","bytea","bytea","bytea","text","text","text","text","text","timestamp with time zone","boolean"],"argtypes":["bytea","bytea","bytea","bytea","numeric","numeric","bytea","bytea","bytea","bytea"],"firma":"vec_autorizacion_atestada_v3.registrar_y_consumir_mi_bolsa_v3_atestada(bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)","language":"plpgsql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_language","refobjsubid":0,"target":{"identity":"plpgsql","name":"plpgsql","schema":null,"type":"language"}},{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":["i","i","i","i","i","i","i","i","i","i","t","t","t","t","t","t","t"],"proargnames":["p_capacidad","p_decision","p_motivo","p_contexto","p_persona_version","p_perfil_version","p_payload","p_sobre","p_evidencia","p_raiz","decision_ref","efecto_ref","huella_efecto_sha256","consumo_huella_sha256","auditoria_ref","consumida_en","consumo_nuevo"],"probin":null,"proconfig":["search_path=pg_catalog","lock_timeout=2s"],"procost":100,"proisstrict":false,"prokind":"f","proleakproof":false,"proname":"registrar_y_consumir_mi_bolsa_v3_atestada","pronargdefaults":0,"pronargs":10,"proparallel":"u","proretset":true,"prorows":1000,"prosecdef":true,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"v"},"pg_shdepend":[{"class":"pg_proc","deptype":"a","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_bolsa_llamamientos_propietario","name":"vec_bolsa_llamamientos_propietario","schema":null,"type":"role"}},{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"record","sha_prosrc":"42385414aae57a854ebb4ffd229b6188527b3fd3488d12e0e3bb8d8adb6217a4","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"},{"grantable":false,"grantee":"vec_bolsa_llamamientos_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":["bytea","bytea","bytea","bytea","numeric","numeric","bytea","bytea","bytea","bytea","text","text","text","text","text","timestamp with time zone","boolean"],"argtypes":["bytea","bytea","bytea","bytea","numeric","numeric","bytea","bytea","bytea","bytea"],"firma":"vec_autorizacion_atestada_v3.registrar_y_consumir_portal_candidato_bolsa_v3_atestada(bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)","language":"plpgsql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_language","refobjsubid":0,"target":{"identity":"plpgsql","name":"plpgsql","schema":null,"type":"language"}},{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":["i","i","i","i","i","i","i","i","i","i","t","t","t","t","t","t","t"],"proargnames":["p_capacidad","p_decision","p_motivo","p_contexto","p_persona_version","p_perfil_version","p_payload","p_sobre","p_evidencia","p_raiz","decision_ref","efecto_ref","huella_efecto_sha256","consumo_huella_sha256","auditoria_ref","consumida_en","consumo_nuevo"],"probin":null,"proconfig":["search_path=pg_catalog","lock_timeout=2s"],"procost":100,"proisstrict":false,"prokind":"f","proleakproof":false,"proname":"registrar_y_consumir_portal_candidato_bolsa_v3_atestada","pronargdefaults":0,"pronargs":10,"proparallel":"u","proretset":true,"prorows":1000,"prosecdef":true,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"v"},"pg_shdepend":[{"class":"pg_proc","deptype":"a","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_bolsa_llamamientos_propietario","name":"vec_bolsa_llamamientos_propietario","schema":null,"type":"role"}},{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"record","sha_prosrc":"582e12978066daff2d7bee0abd07bee405a2b72826d8c74de9ee4967767eceee","variadic":null},
{"acl_effective":[{"grantable":false,"grantee":"vec_autorizacion_atestada_v3_propietario","grantor":"vec_autorizacion_atestada_v3_propietario","privilege":"EXECUTE"}],"allargtypes":null,"argtypes":["text"],"firma":"vec_autorizacion_atestada_v3.texto_json_go(text)","language":"sql","owner":"vec_autorizacion_atestada_v3_propietario","pg_depend":[{"class":"pg_proc","deptype":"n","objsubid":0,"refclass":"pg_namespace","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3","name":"vec_autorizacion_atestada_v3","schema":null,"type":"schema"}}],"pg_proc":{"proargdefaults":null,"proargmodes":null,"proargnames":["p_valor"],"probin":null,"proconfig":["search_path=pg_catalog"],"procost":100,"proisstrict":true,"prokind":"f","proleakproof":false,"proname":"texto_json_go","pronargdefaults":0,"pronargs":1,"proparallel":"u","proretset":false,"prorows":0,"prosecdef":false,"prosqlbody":null,"prosupport":"-","protrftypes":null,"provolatile":"i"},"pg_shdepend":[{"class":"pg_proc","deptype":"o","objsubid":0,"refclass":"pg_authid","refobjsubid":0,"target":{"identity":"vec_autorizacion_atestada_v3_propietario","name":"vec_autorizacion_atestada_v3_propietario","schema":null,"type":"role"}}],"return":"text","sha_prosrc":"fc731f9aae3334ac6eb2fd0480cad8044326c526bf57f894d4fb83acc093c67c","variadic":null}
]$matriz$::pg_catalog.jsonb;
 historica pg_catalog.jsonb; actual pg_catalog.jsonb; filas pg_catalog.jsonb;
 e pg_catalog.jsonb; f pg_catalog.oid; antes pg_catalog.pg_proc%ROWTYPE;
 despues pg_catalog.pg_proc%ROWTYPE; configuracion pg_catalog.text[];
 dependencias_antes pg_catalog.jsonb; dependencias_despues pg_catalog.jsonb;
BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_catalog.pg_roles WHERE rolname=current_user AND rolsuper)
 OR pg_catalog.current_setting('transaction_isolation')<>'read committed'
 OR pg_catalog.current_setting('transaction_read_only')<>'off'
 OR pg_catalog.current_setting('server_version_num')::pg_catalog.int4 NOT BETWEEN 180000 AND 189999 THEN
  RAISE EXCEPTION 'AD3-133: migrador o transacción no autorizados' USING ERRCODE='55000';
 END IF;
 -- La variante de copias históricas se forma con dos huellas medidas conjuntamente;
 -- nunca admite elegir la huella de cada función por separado.
 SELECT pg_catalog.jsonb_agg(CASE WHEN v.firma IS NULL THEN x ELSE
  pg_catalog.jsonb_set(x,'{sha_prosrc}',pg_catalog.to_jsonb(v.sha_prosrc)) END ORDER BY x->>'firma')
 INTO historica FROM pg_catalog.jsonb_array_elements(ampliada) x
 LEFT JOIN pg_catalog.jsonb_to_recordset($historia$[{"firma":"vec_autorizacion_atestada_v3.consumir_decision_mutacion_v3_externa_interna(text,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)","sha_prosrc":"d6a85c9a02818f0a87ec7c46fc595b3fa538cc109c80d5da18085b4a5a23e679"},{"firma":"vec_autorizacion_atestada_v3.consumir_decision_mutacion_v3_usuarios_externa_interna(text,bytea,bytea,bytea,bytea,numeric,numeric,bytea,bytea,bytea,bytea)","sha_prosrc":"a823ac4f0406f8f718f3c37164217d95ba85af1c11b0f82c7e05df8ee872dae6"}]$historia$::pg_catalog.jsonb)
 AS v(firma pg_catalog.text,sha_prosrc pg_catalog.text) ON v.firma=x->>'firma';
SELECT pg_catalog.jsonb_agg(entrada ORDER BY entrada->>'firma') INTO actual FROM (
WITH sig(firma) AS (SELECT x->>'firma' FROM pg_catalog.jsonb_array_elements(ampliada) x)
select jsonb_build_object(
 'firma',s.firma,'sha_prosrc',encode(sha256(convert_to(p.prosrc,'UTF8')),'hex'),
 'owner',pg_get_userbyid(p.proowner),'language',l.lanname,
 'argtypes',(select jsonb_agg(format_type(x,null) order by i) from unnest(p.proargtypes::oid[]) with ordinality t(x,i)),
 'allargtypes',(select jsonb_agg(format_type(x,null) order by i) from unnest(p.proallargtypes) with ordinality t(x,i)),
 'return',format_type(p.prorettype,null),'variadic',case when p.provariadic=0 then null else format_type(p.provariadic,null) end,
 'pg_proc',to_jsonb(p)-array['oid','pronamespace','proowner','prolang','proargtypes','proallargtypes','prorettype','provariadic','prosrc','proacl'],
 'acl_effective',coalesce((select jsonb_agg(jsonb_build_object('grantee',coalesce(gr.rolname,'PUBLIC'),'grantor',go.rolname,'privilege',a.privilege_type,'grantable',a.is_grantable) order by coalesce(gr.rolname,'PUBLIC'),go.rolname,a.privilege_type,a.is_grantable) from aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a left join pg_roles gr on gr.oid=a.grantee left join pg_roles go on go.oid=a.grantor),'[]'::jsonb),
 'pg_depend',coalesce((select jsonb_agg(jsonb_build_object('class',d.classid::regclass::text,'objsubid',d.objsubid,'refclass',d.refclassid::regclass::text,'refobjsubid',d.refobjsubid,'deptype',d.deptype,'target',to_jsonb(i)) order by d.classid::regclass::text,d.objsubid,d.refclassid::regclass::text,d.refobjsubid,d.deptype,i.identity) from pg_depend d cross join lateral pg_identify_object(d.refclassid,d.refobjid,d.refobjsubid) i where d.classid='pg_proc'::regclass and d.objid=p.oid),'[]'::jsonb),
 'pg_shdepend',coalesce((select jsonb_agg(jsonb_build_object('class',d.classid::regclass::text,'objsubid',d.objsubid,'refclass',d.refclassid::regclass::text,'refobjsubid',0,'deptype',d.deptype,'target',to_jsonb(i)) order by d.classid::regclass::text,d.objsubid,d.refclassid::regclass::text,d.deptype,i.identity) from pg_shdepend d cross join lateral pg_identify_object(d.refclassid,d.refobjid,0) i where d.classid='pg_proc'::regclass and d.objid=p.oid and d.dbid=(select oid from pg_database where datname=current_database())),'[]'::jsonb)
) from sig s join pg_proc p on p.oid=to_regprocedure(s.firma) join pg_language l on l.oid=p.prolang
) AS conjunto(entrada);
 IF pg_catalog.jsonb_array_length(actual) IS DISTINCT FROM 17
 OR (actual IS DISTINCT FROM ampliada AND actual IS DISTINCT FROM historica) THEN
  RAISE EXCEPTION 'AD3-133: preimagen global incompatible' USING ERRCODE='55000';
 END IF;
 -- Capturar el catálogo completo con sus OID locales antes del primer ALTER.
 SELECT pg_catalog.jsonb_agg(pg_catalog.to_jsonb(p) ORDER BY p.oid)
 INTO filas FROM pg_catalog.pg_proc p
 WHERE p.oid IN(SELECT pg_catalog.to_regprocedure(x->>'firma') FROM pg_catalog.jsonb_array_elements(ampliada) x);
 SELECT pg_catalog.jsonb_build_object(
 'locales',(SELECT pg_catalog.jsonb_agg(pg_catalog.to_jsonb(d) ORDER BY d.classid,d.objid,d.objsubid,d.refclassid,d.refobjid,d.refobjsubid,d.deptype)
 FROM pg_catalog.pg_depend d WHERE d.classid='pg_catalog.pg_proc'::pg_catalog.regclass
 AND d.objid IN(SELECT (x->>'oid')::pg_catalog.oid FROM pg_catalog.jsonb_array_elements(filas) x)),
 'compartidas',(SELECT pg_catalog.jsonb_agg(pg_catalog.to_jsonb(d) ORDER BY d.dbid,d.classid,d.objid,d.objsubid,d.refclassid,d.refobjid,d.deptype)
 FROM pg_catalog.pg_shdepend d WHERE d.classid='pg_catalog.pg_proc'::pg_catalog.regclass
 AND d.dbid=(SELECT oid FROM pg_catalog.pg_database WHERE datname=pg_catalog.current_database())
 AND d.objid IN(SELECT (x->>'oid')::pg_catalog.oid FROM pg_catalog.jsonb_array_elements(filas) x))) INTO dependencias_antes;
 FOR e IN SELECT x FROM pg_catalog.jsonb_array_elements(filas) x LOOP
  f:=(e->>'oid')::pg_catalog.oid;
  SELECT p.* INTO STRICT antes FROM pg_catalog.pg_proc p WHERE p.oid=f;
  IF pg_catalog.to_jsonb(antes) IS DISTINCT FROM e THEN
   RAISE EXCEPTION 'AD3-133: preimagen concurrente incompatible' USING ERRCODE='55000';
  END IF;
  SELECT pg_catalog.array_agg(CASE WHEN opcion='search_path=pg_catalog' THEN 'search_path=pg_catalog, pg_temp' ELSE opcion END ORDER BY indice)
  INTO configuracion FROM pg_catalog.unnest(antes.proconfig) WITH ORDINALITY AS opciones(opcion,indice);
  EXECUTE pg_catalog.format('ALTER FUNCTION %s SET search_path=pg_catalog,pg_temp',f::pg_catalog.regprocedure);
  SELECT p.* INTO STRICT despues FROM pg_catalog.pg_proc p WHERE p.oid=f;
  IF pg_catalog.to_jsonb(despues)-'proconfig' IS DISTINCT FROM e-'proconfig'
  OR despues.proconfig IS DISTINCT FROM configuracion THEN
   RAISE EXCEPTION 'AD3-133: postimagen incompatible' USING ERRCODE='55000';
  END IF;
 END LOOP;
 SELECT pg_catalog.jsonb_build_object(
 'locales',(SELECT pg_catalog.jsonb_agg(pg_catalog.to_jsonb(d) ORDER BY d.classid,d.objid,d.objsubid,d.refclassid,d.refobjid,d.refobjsubid,d.deptype)
 FROM pg_catalog.pg_depend d WHERE d.classid='pg_catalog.pg_proc'::pg_catalog.regclass
 AND d.objid IN(SELECT (x->>'oid')::pg_catalog.oid FROM pg_catalog.jsonb_array_elements(filas) x)),
 'compartidas',(SELECT pg_catalog.jsonb_agg(pg_catalog.to_jsonb(d) ORDER BY d.dbid,d.classid,d.objid,d.objsubid,d.refclassid,d.refobjid,d.deptype)
 FROM pg_catalog.pg_shdepend d WHERE d.classid='pg_catalog.pg_proc'::pg_catalog.regclass
 AND d.dbid=(SELECT oid FROM pg_catalog.pg_database WHERE datname=pg_catalog.current_database())
 AND d.objid IN(SELECT (x->>'oid')::pg_catalog.oid FROM pg_catalog.jsonb_array_elements(filas) x))) INTO dependencias_despues;
 IF dependencias_despues IS DISTINCT FROM dependencias_antes THEN
  RAISE EXCEPTION 'AD3-133: dependencias alteradas' USING ERRCODE='55000';
 END IF;
END $convergencia$;
COMMIT;
