package main

const plantillaInforme = `<!doctype html>
<html lang="{{.Idioma}}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>{{.Textos.titulo}}</title><style>{{.CSS}}</style></head>
<body class="informe-organizacion"><header class="informe-cabecera"><h1>{{.Textos.titulo}}</h1><p class="aviso">{{.Textos.aviso}}</p></header><main>
<section class="panel" aria-labelledby="cortes"><div class="cabecera-panel"><h2 id="cortes">{{.Textos.cortes}}</h2></div><div class="cuerpo-panel cortes">
<div><h3>{{.Textos.antes}}</h3><dl><dt>{{.Textos.vigente_en}}</dt><dd>{{.Antes.Fecha}}</dd><dt>{{.Textos.conocido_en}}</dt><dd>{{.Antes.Conocido}}</dd><dt>{{.Textos.version_rpt_ref}}</dt><dd>{{.Antes.RPT}}</dd><dt>{{.Textos.version_plantilla_ref}}</dt><dd>{{.Antes.Plantilla}}</dd></dl></div>
<div><h3>{{.Textos.despues}}</h3><dl><dt>{{.Textos.vigente_en}}</dt><dd>{{.Despues.Fecha}}</dd><dt>{{.Textos.conocido_en}}</dt><dd>{{.Despues.Conocido}}</dd><dt>{{.Textos.version_rpt_ref}}</dt><dd>{{.Despues.RPT}}</dd><dt>{{.Textos.version_plantilla_ref}}</dt><dd>{{.Despues.Plantilla}}</dd></dl></div>
</div></section>
<section class="panel" aria-labelledby="resumen"><div class="cabecera-panel"><h2 id="resumen">{{.Textos.resumen}}</h2></div><div class="cuerpo-panel"><p>{{.Textos.limite}}</p><div class="tabla-scroll" tabindex="0" role="region" aria-labelledby="resumen"><table><thead><tr><th scope="col">{{.Textos.coleccion}}</th><th scope="col">{{.Textos.registros_recibidos}} · {{.Textos.antes}}</th><th scope="col">{{.Textos.registros_recibidos}} · {{.Textos.despues}}</th><th scope="col">{{.Textos.cobertura}} · {{.Textos.antes}}</th><th scope="col">{{.Textos.cobertura}} · {{.Textos.despues}}</th><th scope="col">{{.Textos.cambios}}</th><th scope="col">{{.Textos.sin_verificar}}</th></tr></thead><tbody>
{{range .Colecciones}}<tr><th scope="row"><a href="#{{.Clave}}">{{.Nombre}}</a></th><td class="numero">{{n .Antes}}</td><td class="numero">{{n .Despues}}</td><td>{{.CoberturaAntes}}</td><td>{{.CoberturaDespues}}</td><td class="numero">{{n (len .Cambios)}}</td><td class="numero">{{n (len .NoVerificables)}}</td></tr>{{end}}
</tbody></table></div></div></section>
{{range .Colecciones}}<section class="panel" aria-labelledby="{{.Clave}}"><div class="cabecera-panel"><h2 id="{{.Clave}}">{{.Nombre}}</h2></div><div class="cuerpo-panel">
{{if .Cambios}}<div class="tabla-scroll" tabindex="0" role="region" aria-labelledby="{{.Clave}}"><table><thead><tr><th scope="col">{{$.Textos.nombre}}</th><th scope="col">{{$.Textos.tipo_cambio}}</th><th scope="col">{{$.Textos.campo}}</th><th scope="col">{{$.Textos.antes}}</th><th scope="col">{{$.Textos.despues}}</th></tr></thead><tbody>
{{range .Cambios}}{{$fila := .}}{{range .Campos}}<tr><th scope="row">{{$fila.Nombre}}</th><td>{{$fila.Tipo}}</td><td>{{.Campo}}</td><td>{{.Antes}}</td><td>{{.Despues}}</td></tr>{{end}}
<tr><td colspan="5"><details><summary>{{$.Textos.traza}} · {{.Nombre}}</summary><p>{{.ID}}</p><pre>{{.Traza}}</pre></details></td></tr>{{end}}
</tbody></table></div>{{else}}<p>{{$.Textos.sin_cambios}}</p>{{end}}
{{if .NoVerificables}}<p class="aviso">{{$.Textos.no_verificable}} · {{n (len .NoVerificables)}}</p><details><summary>{{$.Textos.sin_verificar}}</summary><ul>{{range .NoVerificables}}<li>{{.}}</li>{{end}}</ul></details>{{end}}
</div></section>{{end}}
<section class="panel"><div class="cuerpo-panel"><details id="detalle-manifiesto"><summary>{{.Textos.detalle}}</summary><dl><dt>{{.Textos.huella}}</dt><dd id="huella-manifiesto">{{.Huella}}</dd><dt>{{.Textos.organismo_ref}}</dt><dd>{{.Antes.Organismo}}</dd><dt>{{.Textos.unidad_clave}}</dt><dd>{{.Antes.Unidad}}</dd></dl><pre id="manifiesto">{{.Manifiesto}}</pre></details></div></section>
</main></body></html>`

const estiloInforme = `
*{box-sizing:border-box}body.informe-organizacion{height:100dvh;display:grid;grid-template-rows:auto minmax(0,1fr);overflow:hidden;margin:0;font:14px/1.5 system-ui,sans-serif;color:var(--portal-tinta);background:var(--portal-fondo)}
.informe-cabecera,.informe-organizacion main{width:100%;max-width:1360px;margin:0 auto;padding:24px}h1{font-size:26px;font-weight:600;margin:0 0 16px}h3{font-size:18px;font-weight:600;margin:0 0 12px}.informe-organizacion main{min-height:0;overflow:auto;display:grid;grid-auto-rows:max-content;align-content:start;gap:24px;padding-top:0}.aviso{padding:12px 16px;background:var(--portal-aviso-suave);color:var(--portal-aviso);border-left:4px solid var(--portal-aviso);margin:0 0 16px}.cortes{display:grid;grid-template-columns:1fr 1fr;gap:24px}dl{display:grid;grid-template-columns:minmax(120px,1fr) minmax(0,2fr);gap:8px 16px;margin:0}dt{color:var(--portal-muted)}dd{margin:0;overflow-wrap:anywhere}.tabla-scroll{max-height:640px;overflow:auto;max-width:100%}table{border-collapse:collapse;width:100%;min-width:760px;text-align:left}th,td{padding:12px;border-bottom:1px solid var(--portal-borde);vertical-align:top}thead th{font-weight:600;color:var(--portal-muted);background:var(--portal-superficie-alterna);position:sticky;top:0}th{font-weight:600}td{max-width:280px;overflow-wrap:anywhere}.numero{text-align:right;font-variant-numeric:tabular-nums}a{color:var(--portal-azul-700)}summary{cursor:pointer;min-height:32px;padding:4px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;max-width:100%;margin:12px 0}p{margin-top:0}:focus-visible{outline:3px solid var(--portal-foco);outline-offset:3px}
@media(max-width:680px){.informe-cabecera,.informe-organizacion main{width:100%;padding:16px}.informe-organizacion main{padding-top:0;gap:16px}.cortes{grid-template-columns:1fr}.cuerpo-panel{padding:16px}.cabecera-panel{padding:12px 16px}dl{grid-template-columns:1fr;gap:4px}dd{margin-bottom:8px}h1{font-size:24px}}
@media print{body.informe-organizacion{height:auto;overflow:visible;display:block;background:var(--portal-superficie)}.informe-cabecera,.informe-organizacion main{width:100%;max-width:none;padding:12px}.informe-organizacion main{overflow:visible;display:block}.panel{box-shadow:none;break-inside:avoid;margin-bottom:16px}.tabla-scroll{overflow:visible;max-height:none}table{min-width:0;font-size:10px}thead th{position:static}th,td{padding:6px}details pre{font-size:9px}}
`
